// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4BKPPgOne7Q0car_1ZybCIaB-7zPC4o0',
    appId: '1:995118722007:web:93c263d008ab634758b992',
    messagingSenderId: '995118722007',
    projectId: 'psut-mybus',
    authDomain: 'psut-mybus.firebaseapp.com',
    storageBucket: 'psut-mybus.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlL2wn-2IwUPS90TUcurjEeaybPs25fow',
    appId: '1:995118722007:android:1ec7f13d55125d3f58b992',
    messagingSenderId: '995118722007',
    projectId: 'psut-mybus',
    storageBucket: 'psut-mybus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNh6zKS3-zYYHDh5avMGuF8LV5RP6_67Y',
    appId: '1:995118722007:ios:3820b7aca650d92458b992',
    messagingSenderId: '995118722007',
    projectId: 'psut-mybus',
    storageBucket: 'psut-mybus.appspot.com',
    iosBundleId: 'com.example.myBusPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNh6zKS3-zYYHDh5avMGuF8LV5RP6_67Y',
    appId: '1:995118722007:ios:e1a4719f978d4b2958b992',
    messagingSenderId: '995118722007',
    projectId: 'psut-mybus',
    storageBucket: 'psut-mybus.appspot.com',
    iosBundleId: 'com.example.myBusPortal.RunnerTests',
  );
}
